p8105_hw2_yl5508
================
Yifei LIU
2023/9/30

It’s a proj for HW2 about DATA WRANGLING.

## Problem 1

### Problem 1.1 DATA CLEANING

``` r
pols_data =
  read_csv("./datastore/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"), "-") |>
  mutate(month = month.name[as.numeric(month)]) |>
  #the same as
  #mutate(month = case_match(month, case_match(month,"01"~"Jan"), ...)
  #OR using
  #mutate(month = case_when(month=="01"~"Jan"), ...)
  mutate(president = case_when(
    prez_gop != "0" ~ "gop",
    prez_dem != "0" ~ "dem"
  )) |>
  select(-c("day", "prez_gop", "prez_dem")) |>
  select(year, month, president, everything())
head(pols_data, 5)
```

    ## # A tibble: 5 × 9
    ##   year  month    president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##   <chr> <chr>    <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ## 1 1947  January  dem            23      51     253      23      45     198
    ## 2 1947  February dem            23      51     253      23      45     198
    ## 3 1947  March    dem            23      51     253      23      45     198
    ## 4 1947  April    dem            23      51     253      23      45     198
    ## 5 1947  May      dem            23      51     253      23      45     198

**1.1.1** `pols_data` is from `pols-month.csv`, with 822 obs. and 9
variables.  
Break the variable `mon` into three variables `y`, `m`, `day`, then
remove the first two variables.  
Variables are arranged in order of `year`, `month`, `president`, … .

``` r
snp_data =
  read_csv("./datastore/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c("month", "day", "year"), "/") |>
  mutate(year = as.numeric(year)) |>
  mutate(year = ifelse(year >= 30 & year <= 99,  1900+year, 2000+year)) |>
  mutate(year = as.character(year)) |>
  mutate(month = month.name[as.numeric(month)]) |>
  select(-day) |>
  select(year, month, everything())
head(snp_data, 5)
```

    ## # A tibble: 5 × 3
    ##   year  month close
    ##   <chr> <chr> <dbl>
    ## 1 2015  July  2080.
    ## 2 2015  June  2063.
    ## 3 2015  May   2107.
    ## 4 2015  April 2086.
    ## 5 2015  March 2068.

**1.1.2** `snp_data` is from `snp.csv`, with 787 obs. and 3 variables.  
Use function `ifelse()` to correct year format, then switch it back to
character type.  
Turn variable `month` from number into month.name format.  
Variables are arranged in order of `year`, `month`, `close`.

``` r
unemployment_data =
  read_csv("./datastore/unemployment.csv") |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment_rate"
  ) |>
  mutate(month = month.name[match(str_to_title(month), month.abb)]) |>
  select(year, month, everything())
head(unemployment_data, 5)
```

    ## # A tibble: 5 × 3
    ##    year month    unemployment_rate
    ##   <dbl> <chr>                <dbl>
    ## 1  1948 January                3.4
    ## 2  1948 February               3.8
    ## 3  1948 March                  4  
    ## 4  1948 April                  3.9
    ## 5  1948 May                    3.5

**1.1.3** `unemployment_data` is from `unemployment.csv`, with 816 obs.
and 3 variables.  
Reorganize the dataset by creating two new variables `month` and
`unemployment`, using function `pivot_longer()`.  
Variables are arranged in order of `year`, `month`, `unemployment_rate`.

### Problem 1.2 JOINING DATASETS

Create variable `year_month` combining variable `year` and `month`, then
merge the data by variable `year_month`.

``` r
pols_join =
  pols_data |>
  mutate(year_month = paste(year, month, sep = "-")) |>
  select(year_month, everything())

snp_join =
  snp_data |>
  mutate(year_month = paste(year, month, sep = "-")) |>
  select(year_month, everything())

unemployment_join =
  unemployment_data |>
  mutate(year_month = paste(year, month, sep = "-")) |>
  select(year_month, everything())

pols_snp = left_join(pols_join, snp_join, by = "year_month") |>
  select(-year.y, -month.y) |>
  select(year_month, year = year.x, month = month.x, president, close, everything()) |>
  arrange(year)
head(pols_snp, 5)
```

    ## # A tibble: 5 × 11
    ##   year_month year  month president close gov_gop sen_gop rep_gop gov_dem sen_dem
    ##   <chr>      <chr> <chr> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ## 1 1947-Janu… 1947  Janu… dem          NA      23      51     253      23      45
    ## 2 1947-Febr… 1947  Febr… dem          NA      23      51     253      23      45
    ## 3 1947-March 1947  March dem          NA      23      51     253      23      45
    ## 4 1947-April 1947  April dem          NA      23      51     253      23      45
    ## 5 1947-May   1947  May   dem          NA      23      51     253      23      45
    ## # ℹ 1 more variable: rep_dem <dbl>

``` r
pols_snp_unemployment = left_join(pols_snp, unemployment_join, by = "year_month") |>
  select(-year.y, -month.y) |>
  select(year_month, year = year.x, month = month.x, president, close, unemployment_rate, everything()) |>
  arrange(year)
head(pols_snp_unemployment, 5)
```

    ## # A tibble: 5 × 12
    ##   year_month    year  month    president close unemployment_rate gov_gop sen_gop
    ##   <chr>         <chr> <chr>    <chr>     <dbl>             <dbl>   <dbl>   <dbl>
    ## 1 1947-January  1947  January  dem          NA                NA      23      51
    ## 2 1947-February 1947  February dem          NA                NA      23      51
    ## 3 1947-March    1947  March    dem          NA                NA      23      51
    ## 4 1947-April    1947  April    dem          NA                NA      23      51
    ## 5 1947-May      1947  May      dem          NA                NA      23      51
    ## # ℹ 4 more variables: rep_gop <dbl>, gov_dem <dbl>, sen_dem <dbl>,
    ## #   rep_dem <dbl>

### Problem 1.3 DATA REVIEW

We can use `skim()` to grab some key characters of the dataset.

``` r
skimr::skim(pols_snp_unemployment)
```

|                                                  |                       |
|:-------------------------------------------------|:----------------------|
| Name                                             | pols_snp_unemployment |
| Number of rows                                   | 822                   |
| Number of columns                                | 12                    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                       |
| Column type frequency:                           |                       |
| character                                        | 4                     |
| numeric                                          | 8                     |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                       |
| Group variables                                  | None                  |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| year_month    |         0 |             1 |   8 |  14 |     0 |      822 |          0 |
| year          |         0 |             1 |   4 |   4 |     0 |       69 |          0 |
| month         |         0 |             1 |   3 |   9 |     0 |       12 |          0 |
| president     |         0 |             1 |   3 |   3 |     0 |        2 |          0 |

**Variable type: numeric**

| skim_variable     | n_missing | complete_rate |  mean |    sd |    p0 |   p25 |   p50 |   p75 | p100 | hist  |
|:------------------|----------:|--------------:|------:|------:|------:|------:|------:|------:|-----:|:------|
| close             |        36 |          0.96 | 472.9 | 543.3 |  17.1 |  83.7 | 137.3 | 932.1 | 2107 | ▇▁▂▁▁ |
| unemployment_rate |        12 |          0.99 |   5.8 |   1.6 |   2.5 |   4.7 |   5.6 |   6.9 |   11 | ▃▇▅▂▁ |
| gov_gop           |         0 |          1.00 |  22.5 |   5.7 |  12.0 |  18.0 |  22.0 |  28.0 |   34 | ▆▆▇▅▅ |
| sen_gop           |         0 |          1.00 |  46.1 |   6.4 |  32.0 |  42.0 |  46.0 |  51.0 |   56 | ▃▃▇▇▇ |
| rep_gop           |         0 |          1.00 | 194.9 |  29.2 | 141.0 | 176.0 | 195.0 | 222.0 |  253 | ▃▇▆▃▅ |
| gov_dem           |         0 |          1.00 |  27.2 |   5.9 |  17.0 |  22.0 |  28.0 |  32.0 |   41 | ▆▅▇▆▂ |
| sen_dem           |         0 |          1.00 |  54.4 |   7.4 |  44.0 |  48.0 |  53.0 |  58.0 |   71 | ▇▆▇▃▂ |
| rep_dem           |         0 |          1.00 | 245.0 |  31.4 | 188.0 | 211.0 | 250.0 | 268.0 |  301 | ▇▂▇▇▅ |

1)  `pols_data` contains 822 obs. of 9 variables. The key variables are
    `year`, `month`, `president`.  
2)  `snp_data` contains 787 obs. of 3 variables. The key variables are
    `year`, `month`, `close`.  
3)  `unemployment_data` contains 816 obs. of 3 variables. The key
    variables are `year`, `month`, `unemployment_rate`.

## Problem 2

### Problem 2.1 DATA CLEANING

``` r
mrt_data =
  read_excel("./datastore/202309 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N586") |>
  janitor::clean_names() |>
  separate(date, into=c("y", "m", "day"), sep = "-") |>
  select(-y, -m) |>
  mutate(year = as.character(year)) |>
  mutate(homes_powered = weight_tons*500/30) |>
  mutate(sourcename = "Mr. Trash Wheel") |>
  select(sourcename, dumpster, year, month, day, homes_powered, weight_tons, volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts, plastic_bags, wrappers)
head(mrt_data, 5)
```

    ## # A tibble: 5 × 13
    ##   sourcename      dumpster year  month day   homes_powered weight_tons
    ##   <chr>              <dbl> <chr> <chr> <chr>         <dbl>       <dbl>
    ## 1 Mr. Trash Wheel        1 2014  May   16             71.8        4.31
    ## 2 Mr. Trash Wheel        2 2014  May   16             45.7        2.74
    ## 3 Mr. Trash Wheel        3 2014  May   16             57.5        3.45
    ## 4 Mr. Trash Wheel        4 2014  May   17             51.7        3.1 
    ## 5 Mr. Trash Wheel        5 2014  May   17             67.7        4.06
    ## # ℹ 6 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>

**2.1.1** `mrt_data` is from sheet `Mr. Trash Wheel`, with 584 obs. and
13 variables.  
Break the variable `date` into three variables `y`, `m`, `day`, then
remove the first two variables and get variable `day`.  
Calculate the `homes_powered` using data in `weight_tons`, according to
the given formula.  
Create a label(column `sourcename`) for this dataset.  
Variables are arranged in order of `sourcename`, `dumpster`, `year`,
`month`, `day`, `homes_powered`, `weight_tons` … .

``` r
pro_data =
  read_excel("./datastore/202309 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M108") |>
  janitor::clean_names() |>
  separate(date, into=c("y", "m", "day"), sep = "-") |>
  select(-y, -m) |>
  mutate(year = as.character(year)) |>
  mutate(homes_powered = weight_tons*500/30) |>
  mutate(sourcename = "Professor Trash Wheel") |>
  select(sourcename, dumpster, year, month, day, homes_powered, weight_tons, volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts, plastic_bags, wrappers)
head(pro_data, 5)
```

    ## # A tibble: 5 × 13
    ##   sourcename            dumpster year  month    day   homes_powered weight_tons
    ##   <chr>                    <dbl> <chr> <chr>    <chr>         <dbl>       <dbl>
    ## 1 Professor Trash Wheel        1 2017  January  02             29.8        1.79
    ## 2 Professor Trash Wheel        2 2017  January  30             26.3        1.58
    ## 3 Professor Trash Wheel        3 2017  February 26             38.7        2.32
    ## 4 Professor Trash Wheel        4 2017  February 26             62          3.72
    ## 5 Professor Trash Wheel        5 2017  February 28             24.2        1.45
    ## # ℹ 6 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>

**2.1.2** `pro_data` is from sheet `Professor Trash Wheel`, with 106
obs. and 13 variables.  
Break the variable `date` into three variables `y`, `m`, `day`, then
remove the first two variables and get variable `day`.  
Calculate the `homes_powered` using data in `weight_tons`, according to
the given formula.  
Create a label(column `sourcename`) for this dataset.  
Variables are arranged in order of `sourcename`, `dumpster`, `year`,
`month`, `day`, `homes_powered`, `weight_tons` … .

``` r
gwy_data =
  read_excel("./datastore/202309 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", range = "A2:L157") |>
  janitor::clean_names() |>
  separate(date, into=c("y", "m", "day"), sep = "-") |>
  select(-y, -m) |>
  mutate(year = as.character(year)) |>
  mutate(homes_powered = weight_tons*500/30) |>
  mutate(sourcename = "Gwynnda") |>
  select(sourcename, dumpster, year, month, day, homes_powered, weight_tons, volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts, plastic_bags, wrappers)
head(gwy_data, 5)
```

    ## # A tibble: 5 × 13
    ##   sourcename dumpster year  month day   homes_powered weight_tons
    ##   <chr>         <dbl> <chr> <chr> <chr>         <dbl>       <dbl>
    ## 1 Gwynnda           1 2021  July  03             15.5        0.93
    ## 2 Gwynnda           2 2021  July  07             37.7        2.26
    ## 3 Gwynnda           3 2021  July  07             27          1.62
    ## 4 Gwynnda           4 2021  July  16             29.3        1.76
    ## 5 Gwynnda           5 2021  July  30             25.5        1.53
    ## # ℹ 6 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>

**2.1.3** `gwy_data` is from sheet `Gwynnda Trash Wheel`, with 155 obs.
and 13 variables.  
Break the variable `date` into three variables `y`, `m`, `day`, then
remove the first two variables and get variable `day`.  
Calculate the `homes_powered` using data in `weight_tons`, according to
the given formula.  
Create a label(column `sourcename`) for this dataset.  
Variables are arranged in order of `sourcename`, `dumpster`, `year`,
`month`, `day`, `homes_powered`, `weight_tons` … .

**2.1.4** Then merge all three datasets together.

``` r
total_trash_data = 
  bind_rows(mrt_data, pro_data, gwy_data) |>
  arrange(year, match(month, month.name), day)
head(total_trash_data, 5)
```

    ## # A tibble: 5 × 13
    ##   sourcename      dumpster year  month day   homes_powered weight_tons
    ##   <chr>              <dbl> <chr> <chr> <chr>         <dbl>       <dbl>
    ## 1 Mr. Trash Wheel        1 2014  May   16             71.8        4.31
    ## 2 Mr. Trash Wheel        2 2014  May   16             45.7        2.74
    ## 3 Mr. Trash Wheel        3 2014  May   16             57.5        3.45
    ## 4 Mr. Trash Wheel        4 2014  May   17             51.7        3.1 
    ## 5 Mr. Trash Wheel        5 2014  May   17             67.7        4.06
    ## # ℹ 6 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>

### Problem 2.2 DATA REVIEW

We can use `skim()` to grab some key characters of the dataset.

``` r
skimr::skim(total_trash_data)
```

|                                                  |                  |
|:-------------------------------------------------|:-----------------|
| Name                                             | total_trash_data |
| Number of rows                                   | 845              |
| Number of columns                                | 13               |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                  |
| Column type frequency:                           |                  |
| character                                        | 4                |
| numeric                                          | 9                |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                  |
| Group variables                                  | None             |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| sourcename    |         0 |             1 |   7 |  21 |     0 |        3 |          0 |
| year          |         0 |             1 |   4 |   4 |     0 |       10 |          0 |
| month         |         0 |             1 |   3 |   9 |     0 |       14 |          0 |
| day           |         0 |             1 |   2 |   2 |     0 |       31 |          0 |

**Variable type: numeric**

| skim_variable      | n_missing | complete_rate |  mean |       sd |     p0 |    p25 |    p50 |     p75 |     p100 | hist  |
|:-------------------|----------:|--------------:|------:|---------:|-------:|-------:|-------:|--------:|---------:|:------|
| dumpster           |         0 |          1.00 |   223 |   176.08 |   1.00 |   71.0 |  162.0 |   373.0 |    584.0 | ▇▃▃▃▃ |
| homes_powered      |         0 |          1.00 |    50 |    13.56 |  10.17 |   41.5 |   51.2 |    59.0 |     93.7 | ▁▅▇▃▁ |
| weight_tons        |         0 |          1.00 |     3 |     0.81 |   0.61 |    2.5 |    3.1 |     3.5 |      5.6 | ▁▅▇▃▁ |
| volume_cubic_yards |         0 |          1.00 |    15 |     1.35 |   5.00 |   15.0 |   15.0 |    15.0 |     20.0 | ▁▁▁▇▁ |
| plastic_bottles    |         1 |          1.00 |  2296 |  1715.51 |   0.00 | 1000.0 | 1980.0 |  2900.0 |   9830.0 | ▇▆▁▁▁ |
| polystyrene        |         1 |          1.00 |  1631 |  1916.38 |   0.00 |  280.0 |  950.0 |  2400.0 |  11528.0 | ▇▂▁▁▁ |
| cigarette_butts    |         1 |          1.00 | 15592 | 25614.82 |   0.00 | 3200.0 | 5500.0 | 16000.0 | 310000.0 | ▇▁▁▁▁ |
| plastic_bags       |         1 |          1.00 |  1082 |  1490.05 |   0.00 |  280.0 |  680.0 |  1400.0 |  13450.0 | ▇▁▁▁▁ |
| wrappers           |       118 |          0.86 |  2330 |  2892.73 | 180.00 |  840.0 | 1380.0 |  2635.0 |  20100.0 | ▇▁▁▁▁ |

1)  The total number of observations in result dataset is 845. Variables
    number in result dataset is 13.
2)  The variables included in dataset are `sourcename`, `dumpster`,
    `year`, `month`, `day`, `homes_powered`, `weight_tons`,
    `volume_cubic_yards`, `plastic_bottles`, `polystyrene`,
    `cigarette_butts`, `plastic_bags`, `wrappers`. Key variables `year`,
    `month`, `day` indicate the record time, `weight_tons` indicates the
    amount of trash collected, `homes_powered` indicates number of homes
    being powered by using trash recycle tech, and `sourcename`
    indicates from which sheet we get the corresponding data.
3)  Total weight collected by Professor Trash Wheel is 216.26 (or using
    another formula ).
4)  Total number of cigarette butts collected by Gwynnda in July of 2021
    is 16300.

## Problem 3

### Problem 3.1 DATA CLEANING

For dataset `mci_baseline.csv` and `mci_amyloid.csv`, we notice that
there’re two rows delineating info of the data. During cleaning process,
we shall skip them in order to grab the raw data we want.

``` r
bas_data_clean =
  read_csv("./datastore/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |>
  mutate(sex = case_when(
    sex == 1 ~ "Male",
    sex == 0 ~ "Female"
  )) |>
  mutate(apoe4 = case_when(
    apoe4 == 1 ~ "carrier",
    apoe4 == 0 ~ "non-carrier"
  )) |>
  mutate(age_at_onset = ifelse(age_at_onset == '.', NA, age_at_onset)) |>
  filter(current_age < age_at_onset | is.na(age_at_onset)) |>
  mutate(age_at_onset = as.numeric(age_at_onset))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(bas_data_clean, 5)
```

    ## # A tibble: 5 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ## 1     1        63.1 Female        16 carrier             NA  
    ## 2     2        65.6 Female        20 carrier             NA  
    ## 3     3        62.5 Male          16 carrier             66.8
    ## 4     4        69.8 Female        16 non-carrier         NA  
    ## 5     5        66   Male          16 non-carrier         68.7

``` r
bas_data_dropna =
  bas_data_clean |>
  drop_na(age_at_onset)
head(bas_data_dropna)
```

    ## # A tibble: 6 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ## 1     3        62.5 Male          16 carrier             66.8
    ## 2     5        66   Male          16 non-carrier         68.7
    ## 3     7        66.5 Male          18 non-carrier         74  
    ## 4    13        63.1 Male          12 carrier             69  
    ## 5    14        58.4 Female        20 non-carrier         66.2
    ## 6    18        67.8 Male          16 non-carrier         69.8

``` r
bas_data =
  read_csv("./datastore/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |>
  mutate(sex = case_when(
    sex == 1 ~ "Male",
    sex == 0 ~ "Female"
  )) |>
  mutate(apoe4 = case_when(
    apoe4 == 1 ~ "carrier",
    apoe4 == 0 ~ "non-carrier"
  )) |>
  mutate(age_at_onset = ifelse(age_at_onset == '.', NA, age_at_onset))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(bas_data, 5)
```

    ## # A tibble: 5 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>       <chr>       
    ## 1     1        63.1 Female        16 carrier     <NA>        
    ## 2     2        65.6 Female        20 carrier     <NA>        
    ## 3     3        62.5 Male          16 carrier     66.8        
    ## 4     4        69.8 Female        16 non-carrier <NA>        
    ## 5     5        66   Male          16 non-carrier 68.7

``` r
amy_data =
  read_csv("./datastore/mci_amyloid.csv", skip = 1) |>
  janitor::clean_names() |>
  select(id = study_id, year_0 = baseline, year_2 = time_2, year_4 = time_4, year_6 = time_6, year_8 = time_8) |>
  pivot_longer(
    year_0:year_8,
    names_to = "time",
    values_to = "ratio"
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(amy_data, 5)
```

    ## # A tibble: 5 × 3
    ##      id time   ratio      
    ##   <dbl> <chr>  <chr>      
    ## 1     1 year_0 0.1105487  
    ## 2     1 year_2 <NA>       
    ## 3     1 year_4 0.109325197
    ## 4     1 year_6 0.104756131
    ## 5     1 year_8 0.107257697

### Problem 3.2 DATA REVIEW

1)  There’re 483 participants recruited in the research. From the data,
    we notice 93 participants develop MCI (deem NA as healthy condition,
    with NA the number would be 479).
2)  The average baseline age is 65.03. For participants developing MCI,
    the average baseline age is 65.54.
3)  The proportion of women are APOE4 carriers is 0.3.
4)  

``` r
#manipulate in dataset
baseline_only = anti_join(bas_data_clean, amy_data, by = "id")
amyloid_only = anti_join(amy_data, bas_data_clean, by = "id")
```

``` r
#grab diff data
only_baseline = setdiff(bas_data_clean$id, amy_data$id)
only_amyloid = setdiff(amy_data$id, bas_data_clean$id)
```

After processing, 8 participants only appear in baseline dataset. IDs of
these participants are shown below: 14, 49, 92, 179, 268, 304, 389, 412.

16 participants only appear in baseline dataset. IDs of these
participants are shown below: 72, 234, 283, 380, 484, 485, 486, 487,
488, 489, 490, 491, 492, 493, 494, 495.

5)  

``` r
#combine two datasets into one, with only participants appearing in both datasets
bas_amy = inner_join(bas_data_clean, amy_data, by = "id")
```

There’re 471 participants appear in both dataset. Because ratio data of
each participant is posted for 5 times (in different time intervals), ID
of every participant has been shown 5 times. 8 variables are listed in
combined dataset, included `id`, `current_age`, `sex`, `education`,
`apoe4`, `age_at_onset`, `time`, `ratio`.

6)  The combined data has been saved as `combined_bas_amy.csv`.

``` r
write.csv(bas_amy, file = "./datastore/combined_bas_amy.csv")
```
